name: Kanal 1 Yayin

on:
  workflow_dispatch:

jobs:
  stream:
    runs-on: self-hosted

    steps:
      - name: Kodları çek
        uses: actions/checkout@v4

      - name: Bağımlılıkları kur
        run: pip install requests --break-system-packages || pip install requests

      - name: Yayını başlat
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          CHANNEL_NAME: "kanal1"
          GIST_ID: "34df90330e4b0daeed9a5b516c1c368d"
          STREAM_KEY: "inbox1"
          M3U_FILE: "pars.m3u"
          LOGO_FILE: "1787069925822.png"
        run: exec python3 inbox1.py
